### ISSUE TITLE
[BUG] Docker Fails, multi-threading error???

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/petdeface#4]
To reproduce, launch docker container with appropriate mount to input folder, output folder, project folder, and freesurfer license:

```bash
docker run --rm  -it 
-v /Users/user/Data/ds004230:/input 
-v /Users/user/Data/petdefacetestoutput:/output 
-v /Users/user/Projects/petdeface/petdeface:/project/petdeface 
-v /Applications/freesurfer/7.3.2/license.txt:/opt/freesurfer/license.txt --platform linux/amd64 petdeface:latest /bin/bash
```

Launch pipeline in container

```bash
python3 /petdeface/petdeface/petdeface.py  /input --output_dir /output --n_procs 6
```

Error below:

<details>

```bash
02,434 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.select_files" in "/input/deface_pet_workflow/_session_id_baselinebrain_subject_id_PS40/select_files".
230511-15:37:02,437 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.select_files" in "/input/deface_pet_workflow/_session_id_rescanbrain_subject_id_PS40/select_files".
230511-15:37:02,443 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.select_files" in "/input/deface_pet_workflow/_session_id_baselinebrain_subject_id_PS42/select_files".
230511-15:37:02,452 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.select_files" in "/input/deface_pet_workflow/_session_id_rescanbrain_subject_id_PS42/select_files".
230511-15:37:02,458 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.deface_t1w" in "/input/deface_pet_workflow/_session_id_baselinebrain_subject_id_PS19/deface_t1w".
230511-15:37:02,463 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.create_weighted_average_pet" in "/input/deface_pet_workflow/_session_id_baselinebrain_subject_id_PS19/create_weighted_average_pet".
230511-15:37:02,466 nipype.workflow INFO:
         [Node] Executing "select_files" <nipype.interfaces.io.SelectFiles>
230511-15:37:02,471 nipype.workflow INFO:
         [Node] Executing "select_files" <nipype.interfaces.io.SelectFiles>
230511-15:37:02,478 nipype.workflow INFO:
         [Node] Finished "select_files", elapsed time 0.006363s.
230511-15:37:02,479 nipype.workflow INFO:
         [Node] Executing "select_files" <nipype.interfaces.io.SelectFiles>
230511-15:37:02,482 nipype.workflow INFO:
         [Node] Finished "select_files", elapsed time 0.007147s.
230511-15:37:02,491 nipype.workflow INFO:
         [Node] Finished "select_files", elapsed time 0.006281s.
230511-15:37:02,494 nipype.workflow INFO:
         [Node] Executing "select_files" <nipype.interfaces.io.SelectFiles>
230511-15:37:02,505 nipype.workflow INFO:
         [Node] Finished "select_files", elapsed time 0.006141s.
230511-15:37:02,515 nipype.workflow INFO:
         [Node] Executing "create_weighted_average_pet" <nipype.interfaces.utility.wrappers.Function>
230511-15:37:02,515 nipype.workflow INFO:
         [Node] Executing "deface_t1w" <mideface.Mideface>
230511-15:37:04,271 nipype.workflow INFO:
         [Job 18] Completed (deface_pet_workflow.select_files).
230511-15:37:04,275 nipype.workflow INFO:
         [Job 19] Completed (deface_pet_workflow.select_files).
230511-15:37:04,280 nipype.workflow INFO:
         [Job 20] Completed (deface_pet_workflow.select_files).
230511-15:37:04,284 nipype.workflow INFO:
         [Job 21] Completed (deface_pet_workflow.select_files).
230511-15:37:04,293 nipype.workflow INFO:
         [MultiProc] Running 2 tasks, and 42 jobs ready. Free memory (GB): 6.50/6.90, Free processors: 4/6.
                     Currently running:
                       * deface_pet_workflow.create_weighted_average_pet
                       * deface_pet_workflow.deface_t1w
230511-15:37:04,361 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.deface_t1w" in "/input/deface_pet_workflow/_session_id_rescanbrain_subject_id_PS19/deface_t1w".
230511-15:37:04,367 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.create_weighted_average_pet" in "/input/deface_pet_workflow/_session_id_rescanbrain_subject_id_PS19/create_weighted_average_pet".
230511-15:37:04,370 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.deface_t1w" in "/input/deface_pet_workflow/_session_id_baselinebrain_subject_id_PS20/deface_t1w".
230511-15:37:04,374 nipype.workflow INFO:
         [Node] Setting-up "deface_pet_workflow.create_weighted_average_pet" in "/input/deface_pet_workflow/_session_id_baselinebrain_subject_id_PS20/create_weighted_average_pet".
230511-15:37:04,418 nipype.workflow INFO:
         [Node] Executing "create_weighted_average_pet" <nipype.interfaces.utility.wrappers.Function>
230511-15:37:04,425 nipype.workflow INFO:
         [Node] Executing "deface_t1w" <mideface.Mideface>
230511-15:37:04,425 nipype.workflow INFO:
         [Node] Executing "create_weighted_average_pet" <nipype.interfaces.utility.wrappers.Function>
230511-15:37:04,432 nipype.workflow INFO:
         [Node] Executing "deface_t1w" <mideface.Mideface>
230511-15:37:06,287 nipype.workflow INFO:
         [MultiProc] Running 6 tasks, and 38 jobs ready. Free memory (GB): 5.70/6.90, Free processors: 0/6.
                     Currently running:
                       * deface_pet_workflow.create_weighted_average_pet
                       * deface_pet_workflow.deface_t1w
                       * deface_pet_workflow.create_weighted_average_pet
                       * deface_pet_workflow.deface_t1w
                       * deface_pet_workflow.create_weighted_average_pet
                       * deface_pet_workflow.deface_t1w
exception calling callback for <Future at 0x40135affa0 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

</details>

**Comment by bendhouseart** [comment]
Fixed with new docker images and bumped to version 7.4.1 of freesurfer.
