### ISSUE TITLE
Error with Integration; Unable to Broadcast 

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/petdeface#49]
Attempting to diagnose an issue with a subject not passing the pipeline, posting here for visibility.

User encountered error below:

```python 
File "/usr/local/lib64/python3.11/site-packages/numpy/lib/function_base.py", line 4978, in trapz
     ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
            ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (1,1,1,51) (200,200,111,52)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
     runtime = self._run_interface(runtime)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/petdeface/pet.py", line 58, in _run_interface
     wavg = np.trapz(data, x=mid_frames) / (mid_frames[-1] - mid_frames[0])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib64/python3.11/site-packages/numpy/lib/function_base.py", line 4983, in trapz
     ret = add.reduce(d * (y[tuple(slice1)]+y[tuple(slice2)])/2.0, axis)
                      ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ValueError: operands could not be broadcast together with shapes (1,1,1,51) (200,200,111,52)
```

T1w NifTi Header:

```bash
Volume information for sub-pf14/anat/sub-pf14_T1w.nii.gz
          type: nii
    dimensions: 181 x 256 x 256
   voxel sizes: 1.000002, 0.937500, 0.937500
          type: FLOAT (3)
           fov: 181.000
           dof: 1
        xstart: -90.5, xend: 90.5
        ystart: -120.0, yend: 120.0
        zstart: -120.0, zend: 120.0
            TR: 8.11 msec, TE: 0.00 msec, TI: 0.00 msec, flip angle: 0.00 degrees
       nframes: 1
       PhEncDir: UNKNOWN
       FieldStrength: 0.000000
ras xform present
    xform info: x_r =  -0.9994, y_r =   0.0084, z_r =   0.0342, c_r =    -1.5430
              : x_a =   0.0084, y_a =   1.0000, z_a =  -0.0003, c_a =    17.3237
              : x_s =   0.0342, y_s =  -0.0000, z_s =   0.9994, c_s =     4.8804
Orientation   : LAS
Primary Slice Direction: axial

voxel to ras transform:
               -0.9994   0.0079   0.0320    83.7913
                0.0084   0.9375  -0.0002  -103.4014
                0.0342  -0.0000   0.9370  -118.1391
                0.0000   0.0000   0.0000     1.0000

voxel-to-ras determinant -0.878908

ras to voxel transform:
               -0.9994   0.0084   0.0342    88.6457
                0.0090   1.0666  -0.0000   109.5360
                0.0365  -0.0003   1.0660   122.8582
               -0.0000  -0.0000  -0.0000     1.0000
```

PET NifTi header:

```
Volume information for sub-pf14/ses-pf974/pet/sub-pf14_ses-pf974_pet.nii.gz
          type: nii
    dimensions: 200 x 200 x 111 x 53
   voxel sizes: 2.036420, 2.036420, 2.000000
          type: FLOAT (3)
           fov: 407.284
           dof: 1
        xstart: -203.6, xend: 203.6
        ystart: -203.6, yend: 203.6
        zstart: -111.0, zend: 111.0
            TR: 0.00 msec, TE: 0.00 msec, TI: 0.00 msec, flip angle: 0.00 degrees
       nframes: 53
       PhEncDir: UNKNOWN
       FieldStrength: 0.000000
ras xform present
    xform info: x_r =  -1.0000, y_r =   0.0000, z_r =  -0.0000, c_r =    -1.5550
              : x_a =  -0.0000, y_a =   1.0000, z_a =  -0.0000, c_a =   257.0264
              : x_s =   0.0000, y_s =   0.0000, z_s =   1.0000, c_s =  1319.0000
Orientation   : LAS
Primary Slice Direction: axial

voxel to ras transform:
               -2.0364   0.0000  -0.0000   202.0870
               -0.0000   2.0364  -0.0000    53.3844
                0.0000   0.0000   2.0000  1208.0000
                0.0000   0.0000   0.0000     1.0000

voxel-to-ras determinant -8.29401

ras to voxel transform:
               -0.4911  -0.0000  -0.0000    99.2364
               -0.0000   0.4911  -0.0000   -26.2148
               -0.0000  -0.0000   0.5000  -604.0000
               -0.0000  -0.0000  -0.0000     1.0000
```

**Comment by bendhouseart** [comment]
Closed with PR #50
