### ISSUE TITLE
[BUG] Nipype Error on Non-existent T1w

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/petdeface#6]
note that nipype is encountering errors when looking for t1w files that don't exist,
e.g.  in the naming scheme for ds004230 the anat folders (containing t1w's) are only within
the baseline session. Errors are raised for T1w's not existing for the rescan session, see below:

```bash
230602-09:29:36,844 nipype.workflow ERROR:
         Node deface_t1w.a01 failed to run on host MH02276145MLI.
230602-09:29:36,844 nipype.workflow ERROR:
         Saving crash info to /Users/galassiae/Projects/petdeface/crash-20230602-092936-galassiae-deface_t1w.a01-259d03d6-4e35-4b40-b7bd-0cfdbf270296.pklz
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/galassiae/Data/pet_defacing_data/ds004230_faced/deface_pet_workflow/_session_id_rescanbrain_subject_id_PS19/deface_t1w/_0x5e1eb1e0e25d19c963fbd7a0618ce8d7_unfinished.json' -> '/Users/galassiae/Data/pet_defacing_data/ds004230_faced/deface_pet_workflow/_session_id_rescanbrain_subject_id_PS19/deface_t1w/_0x5e1eb1e0e25d19c963fbd7a0618ce8d7.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/galassiae/Library/Caches/pypoetry/virtualenvs/petdeface-glZEKbHu-py3.10/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/Users/galassiae/Library/Caches/pypoetry/virtualenvs/petdeface-glZEKbHu-py3.10/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 542, in run
    shutil.move(hashfile_unfinished, hashfile_unfinished.replace("_unfinished", ""))
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/galassiae/Data/pet_defacing_data/ds004230_faced/deface_pet_workflow/_session_id_rescanbrain_subject_id_PS19/deface_t1w/_0x5e1eb1e0e25d19c963fbd7a0618ce8d7_unfinished.json'
```

Hopefully this is as simple as a fix as popping sessions/folders without t1w's from the list of sessions to be processed and/or filtering the bids/pybids query a bit better.

**Comment by bendhouseart** [comment]
Might be able to safely ignore this, but tbh I'd rather not have this pipeline throwing errors.
